name: Tensorboard
description:  Tensorboard Plugin for CML, with example models and metrics
author: Steve Kiaie
specification_version: 1.0
prototype_version: 1.0
date: "2021-05-26"
api_version: 1

environment_variables:
  PYTHONPATH:
    default: "/home/cdsw"
    description: "Allow Python to find scripts directory when run as CLI"
    prompt_user: false

tasks:
  - type: create_job
    name: Install Dependencies
    entity_label: install_dependencies
    script: cml/install_dependencies.py
    arguments: None
    cpu: 1
    memory: 2
    short_summary: Create a job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3
    
  - type: run_job
    entity_label: install_dependencies
    short_summary: Run the install dependencies job.
    long_summary: Run the install dependencies job.

  - type: create_job
    name: Train KNeighbors
    entity_label: train_kneighbors
    script: scripts/train_kneighbors.py
    arguments: None
    cpu: 1
    memory: 2
    short_summary: Create a training job for a k-nearest neighbors classifier.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3
    
  - type: start_application
    name: Tensorboard UI
    subdomain: tensorboard
    script: cml/tensorboard_ui.py
    short_summary: Launch the Tensorboard UI application
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
